in_channels : 3
out_channels : 3

batch_size : 32
train_data_dir : './maps/train/'
val_data_dir : './maps/test/'

lambda_pixel : 100
patch_num : 16

lr : 0.0002
beta1 : 0.5
beta2 : 0.999

num_epochs : 400

weight_path : './model/'
res_path : './result/'